stages:
  - pre

pre-commit:
  stage: pre
  script:
    - pre-commit run --all-files --verbose --show-diff-on-failure
  image: gitlab-master.nvidia.com:5005/dl/ai-services/python-clients/codeformat:latest
  tags:
  - os/linux
  - type/docker

