hydra:
  searchpath:
    - file:///opt/NeMo/examples/nlp/language_modeling/conf

run:
  name: train_gpt3_126m_tp1_pp1
  results_dir: ${base_results_dir}/${.name}
  time_limit: "04:00:00"
  dependency: "singleton"

trainer:
  num_nodes: 8
  devices: 8
  accelerator: gpu
  precision: bf16
  logger: false
  enable_checkpointing: false
  use_distributed_sampler: false
  max_epochs: null
  max_steps: 600000
  max_time: 00:23:30:00
  log_every_n_steps: 10
  val_check_interval: 1000
  limit_val_batches: 50
  limit_test_batches: 50
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0

exp_manager:
  explicit_log_dir: ${training.run.results_dir}/results
  exp_dir: null
  name: megatron_gpt
  create_wandb_logger: true
  wandb_logger_kwargs:
    project: 126m_ci_convergence
    name: 126m_conv_tp1_pp1
  resume_if_exists: true
  resume_ignore_no_checkpoint: true
  create_checkpoint_callback: true
  checkpoint_callback_params:
    monitor: val_loss
    save_top_k: 2
    mode: min
    always_save_nemo: false
    save_nemo_on_train_end: false
    filename: megatron_gpt--{val_loss:.2f}-{step}-{consumed_samples}
    model_parallel_size: 1
  log_step_timing: true
  step_timing_kwargs:
    sync_cuda: true
    buffer_size: 5

model:
  micro_batch_size: 4
  global_batch_size: 256
  rampup_batch_size: null
  context_parallel_size: 1
  tensor_model_parallel_size: 1
  pipeline_model_parallel_size: 1
  virtual_pipeline_model_parallel_size: null
  resume_from_checkpoint: null
  encoder_seq_length: 2048
  max_position_embeddings: 2048
  num_layers: 12
  hidden_size: 768
  ffn_hidden_size: 3072
  num_attention_heads: 12
  init_method_std: 0.023
  hidden_dropout: 0.1
  attention_dropout: 0.1
  kv_channels: null
  apply_query_key_layer_scaling: true
  layernorm_epsilon: 1.0e-05
  make_vocab_size_divisible_by: 128
  pre_process: true
  post_process: true
  persist_layer_norm: true
  gradient_as_bucket_view: true
  grad_div_ar_fusion: true
  gradient_accumulation_fusion: true
  bias_activation_fusion: true
  bias_dropout_add_fusion: true
  masked_softmax_fusion: true
  fsdp: false
  fsdp_sharding_strategy: full
  fsdp_grad_reduce_dtype: 32
  fsdp_sharded_checkpoint: false
  activations_checkpoint_granularity: null
  activations_checkpoint_method: null
  activations_checkpoint_num_layers: null
  num_micro_batches_with_partial_activation_checkpoints: null
  activations_checkpoint_layers_per_pipeline: null
  sequence_parallel: false
  overlap_p2p_comm: false
  batch_p2p_comm: true
  num_query_groups: null
  tokenizer:
    library: megatron
    type: GPT2BPETokenizer
    model: null
    delimiter: null
    vocab_file: ${data_dir}/bpe/vocab.json
    merge_file: ${data_dir}/bpe/merges.txt
  native_amp_init_scale: 4294967296
  native_amp_growth_interval: 1000
  hysteresis: 2
  fp32_residual_connection: false
  fp16_lm_cross_entropy: false
  megatron_amp_O2: true
  grad_allreduce_chunk_size_mb: 125
  sharp: false
  mcore_gpt: true
  transformer_engine: false
  fp8: false
  fp8_e4m3: false
  fp8_hybrid: true
  fp8_margin: 0
  fp8_interval: 1
  fp8_amax_history_len: 1024
  fp8_amax_compute_algo: max
  fp8_wgrad: true
  ub_tp_comm_overlap: false
  tp_comm_atomic_ag: false
  tp_comm_atomic_rs: false
  seed: 1234
  sync_batch_comm: false
  use_cpu_initialization: false
  onnx_safe: false
  apex_transformer_log_level: 30
  nsys_profile:
    enabled: false
    trace:
    - nvtx
    - cuda
    start_step: 10
    end_step: 10
    ranks:
    - 0
    gen_shape: false
  optim:
    name: distributed_fused_adam
    bucket_cap_mb: 200
    overlap_grad_sync: true
    overlap_param_sync: true
    contiguous_grad_buffer: true
    lr: 0.0006
    weight_decay: 0.1
    betas:
    - 0.9
    - 0.95
    sched:
      name: CosineAnnealing
      warmup_steps: 636
      constant_steps: 100000
      min_lr: 6.0e-05
  data:
    data_impl: mmap
    splits_string: 99990,8,2
    seq_length: 2048
    skip_warmup: true
    num_workers: 2
    dataloader_type: single
    reset_position_ids: false
    reset_attention_mask: false
    eod_mask_loss: false
    index_mapping_dir: null
    data_prefix:
      - .0333
      - ${data_dir}/my-gpt3_00_text_document
      - .0333
      - ${data_dir}/my-gpt3_01_text_document
      - .0333
      - ${data_dir}/my-gpt3_02_text_document
      - .0333
      - ${data_dir}/my-gpt3_03_text_document
      - .0333
      - ${data_dir}/my-gpt3_04_text_document
      - .0333
      - ${data_dir}/my-gpt3_05_text_document
      - .0333
      - ${data_dir}/my-gpt3_06_text_document
      - .0333
      - ${data_dir}/my-gpt3_07_text_document
      - .0333
      - ${data_dir}/my-gpt3_08_text_document
      - .0333
      - ${data_dir}/my-gpt3_09_text_document
      - .0333
      - ${data_dir}/my-gpt3_10_text_document
      - .0333
      - ${data_dir}/my-gpt3_11_text_document
      - .0333
      - ${data_dir}/my-gpt3_12_text_document
      - .0333
      - ${data_dir}/my-gpt3_13_text_document
      - .0333
      - ${data_dir}/my-gpt3_14_text_document
      - .0333
      - ${data_dir}/my-gpt3_15_text_document
      - .0333
      - ${data_dir}/my-gpt3_16_text_document
      - .0333
      - ${data_dir}/my-gpt3_17_text_document
      - .0333
      - ${data_dir}/my-gpt3_18_text_document
      - .0333
      - ${data_dir}/my-gpt3_19_text_document
      - .0333
      - ${data_dir}/my-gpt3_20_text_document
      - .0333
      - ${data_dir}/my-gpt3_21_text_document
      - .0333
      - ${data_dir}/my-gpt3_22_text_document
      - .0333
      - ${data_dir}/my-gpt3_23_text_document
      - .0333
      - ${data_dir}/my-gpt3_24_text_document
      - .0333
      - ${data_dir}/my-gpt3_25_text_document
      - .0333
      - ${data_dir}/my-gpt3_26_text_document
      - .0333
      - ${data_dir}/my-gpt3_27_text_document
      - .0333
      - ${data_dir}/my-gpt3_28_text_document
      - .0334
      - ${data_dir}/my-gpt3_29_text_document