name: autoconf

on:
  pull_request:
    branches:
      - 'master'

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    env:
      working-directory: ./auto_configurator

    steps:
      - name: checkout the repo
        uses: actions/checkout@v3

      - name: install dependencies
        run: |
          pip install -e '.[test]'

      - name: run unit tests
        run: pytest
        working-directory: ${{env.working-directory}}
